# PyAgent stub - Reforged Native surface.
# Exact counterpart of src/GW/agent/agent_bindings.cpp:
#   ProfessionType enum + Profession class + PyAgent class + 15 module-level free functions.

from enum import IntEnum
from typing import List
from typing import Tuple
from typing import overload

class ProfessionType(IntEnum):
    """Exposes GW::Constants::Profession (include/GW/common/constants/constants.h).

    NOTE: the binding also exposes the value `None` (== 0). It cannot be declared
    here because `None` is a Python keyword; reach it with
    `getattr(ProfessionType, "None")`.
    """

    Warrior = 1
    Ranger = 2
    Monk = 3
    Necromancer = 4
    Mesmer = 5
    Elementalist = 6
    Assassin = 7
    Ritualist = 8
    Paragon = 9
    Dervish = 10

class Profession:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, prof: int) -> None: ...
    @overload
    def __init__(self, prof: str) -> None: ...
    def GetName(self) -> str: ...
    def ToInt(self) -> int: ...
    def Set(self, prof: int) -> None: ...
    def Get(self) -> ProfessionType: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class PyAgent:
    # No data members are exposed; the stored agent id is read via GetAgentID().
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, agent_id: int) -> None: ...
    def GetContext(self) -> None: ...
    def GetAgentID(self) -> int: ...
    def GetPlayerNumber(self) -> int: ...
    def GetName(self) -> str: ...
    def GetPrimary(self) -> int: ...
    def GetSecondary(self) -> int: ...
    def GetLevel(self) -> int: ...
    def GetHP(self) -> float: ...
    def GetRotation(self) -> float: ...
    def GetPos(self) -> Tuple[float, float, float]: ...
    def GetIsLiving(self) -> bool: ...
    def GetIsDead(self) -> bool: ...
    def GetIsMoving(self) -> bool: ...
    def GetIsAttacking(self) -> bool: ...
    def GetIsKnockedDown(self) -> bool: ...
    def GetIsCasting(self) -> bool: ...
    def GetAllegiance(self) -> int: ...
    def GetIsGadget(self) -> bool: ...
    def GetIsItem(self) -> bool: ...
    @staticmethod
    def GetTargetId() -> int: ...
    @staticmethod
    def GetControlledCharacterId() -> int: ...
    @staticmethod
    def GetObservingId() -> int: ...

# -- Module-level free functions (modern surface) --
def send_dialog(dialog_id: int) -> bool: ...
def get_observing_id() -> int: ...
def get_controlled_character_id() -> int: ...
def get_target_id() -> int: ...
def get_amount_of_players_in_instance() -> int: ...
def is_observing() -> bool: ...
def change_target(agent_id: int) -> bool:
    """False if the id is 0 or unknown; otherwise the retarget is enqueued on the game thread."""
    ...

def move(x: float, y: float, zplane: int = 0) -> bool: ...
def interact_agent(agent_id: int, call_target: bool = False) -> bool:
    """False only if agent_id is 0; otherwise the interaction is enqueued on the game thread."""
    ...

def call_target(agent_id: int) -> bool:
    """False only if agent_id is 0; otherwise the call is enqueued on the game thread."""
    ...

def get_player_name_by_login_number(login_number: int) -> str: ...
def get_agent_id_by_login_number(login_number: int) -> int: ...
def get_hero_agent_id(hero_index: int) -> int: ...
def get_agent_enc_name(agent_id: int) -> List[int]:
    """Raw encoded name as UTF-16LE bytes (list[int]), including the terminator.
    Empty list when the agent has no encoded name."""
    ...

def get_agent_is_targettable(agent_id: int) -> bool: ...
