# PyCamera stub — Reforged Native surface
# Exact counterpart of src/GW/camera/camera_bindings.cpp.
# Exposes the PyCamera class (legacy surface) + a Point3D helper + modern
# module-level free functions.

from typing import List, Tuple

class Point3D:
    """PyCamera::Vec3 helper. Default-constructed only (py::init<>)."""

    x: float
    y: float
    z: float
    def __init__(self) -> None: ...

class PyCamera:
    look_at_agent_id: int
    yaw: float
    pitch: float
    camera_zoom: float
    max_distance: float
    yaw_right_click: float
    yaw_right_click2: float
    pitch_right_click: float
    distance2: float
    acceleration_constant: float
    time_since_last_keyboard_rotation: float
    time_since_last_mouse_rotation: float
    time_since_last_mouse_move: float
    time_since_last_agent_selection: float
    time_in_the_map: float
    time_in_the_district: float
    yaw_to_go: float
    pitch_to_go: float
    dist_to_go: float
    max_distance2: float
    field_of_view: float
    field_of_view2: float
    h0024: List[int]
    h0070: List[float]
    position: Point3D
    camera_pos_to_go: Point3D
    cam_pos_inverted: Point3D
    cam_pos_inverted_to_go: Point3D
    look_at_target: Point3D
    look_at_to_go: Point3D

    def __init__(self) -> None: ...
    def GetContext(self) -> None: ...
    def SetYaw(self, _yaw: float) -> None: ...
    def SetPitch(self, _pitch: float) -> None: ...
    def SetMaxDist(self, dist: float) -> None: ...
    def SetFieldOfView(self, fov: float) -> None: ...
    def UnlockCam(self, unlock: bool) -> None: ...
    def GetCameraUnlock(self) -> bool: ...
    def ForwardMovement(self, amount: float, true_forward: bool) -> None: ...
    def VerticalMovement(self, amount: float) -> None: ...
    def SideMovement(self, amount: float) -> None: ...
    def RotateMovement(self, angle: float) -> None: ...
    def ComputeCameraPos(self) -> Tuple[float, float, float]: ...
    def UpdateCameraPos(self) -> None: ...
    def SetCameraPos(self, x: float, y: float, z: float) -> None: ...
    def SetLookAtTarget(self, x: float, y: float, z: float) -> None: ...
    def SetFog(self, fog: bool) -> None: ...

# ── Module-level free functions ──
# These call GW::camera directly (not game-thread enqueued) and return the
# underlying bool success flag.
def forward_movement(amount: float, true_forward: bool = False) -> bool: ...
def vertical_movement(amount: float) -> bool: ...
def rotate_movement(angle: float) -> bool: ...
def side_movement(amount: float) -> bool: ...
def set_max_dist(dist: float = 900.0) -> bool: ...
def set_field_of_view(fov: float) -> bool: ...
def compute_cam_pos(dist: float = 0.0) -> Tuple[float, float, float]: ...
def update_camera_pos() -> bool: ...
def get_field_of_view() -> float: ...
def get_yaw() -> float: ...
def unlock_cam(flag: bool) -> bool: ...
def get_camera_unlock() -> bool: ...
def set_fog(flag: bool) -> bool: ...
def get_context_ptr() -> int: ...
