# PyEffects stub — Reforged Native surface
# Exact counterpart of src/GW/effects/effects_bindings.cpp.

from typing import List

class EffectType:
    """Value snapshot of GW::Context::Effect. Read-only; not constructible from Python."""

    skill_id: int
    attribute_level: int
    effect_id: int
    agent_id: int
    duration: float
    timestamp: int
    time_elapsed: int
    time_remaining: int

class BuffType:
    """Value snapshot of GW::Context::Buff. Read-only; not constructible from Python."""

    skill_id: int
    buff_id: int
    target_agent_id: int

class PyEffects:
    """Legacy per-agent surface: PyEffects(agent_id).GetEffects() etc."""

    def __init__(self, agent_id: int) -> None: ...
    def GetEffects(self) -> List[EffectType]: ...
    def GetBuffs(self) -> List[BuffType]: ...
    def GetEffectCount(self) -> int: ...
    def GetBuffCount(self) -> int: ...
    def EffectExists(self, skill_id: int) -> bool: ...
    def BuffExists(self, skill_id: int) -> bool: ...
    # NOTE: the argument is named `skill_id` in the binding but is forwarded to
    # GW::effects::DropBuff as the buff id.
    def DropBuff(self, skill_id: int) -> None: ...
    @staticmethod
    def GetAlcoholLevel() -> int: ...
    @staticmethod
    def ApplyDrunkEffect(intensity: int = 0, tint: int = 0) -> None: ...

# ── Module-level free functions ──
def get_alcohol_level() -> int: ...
def get_drunk_af(intensity: int, tint: int) -> None: ...
def drop_buff(buff_id: int) -> bool: ...
def effect_count(agent_id: int) -> int: ...
def buff_count(agent_id: int) -> int: ...
def effect_exists(agent_id: int, skill_id: int) -> bool: ...
def buff_exists(agent_id: int, skill_id: int) -> bool: ...
def get_effects(agent_id: int) -> List[EffectType]: ...
def get_buffs(agent_id: int) -> List[BuffType]: ...
