# PyItem stub — Reforged Native surface (2026-07-20)
# Exact counterpart of src/GW/item/item_bindings.cpp.
# Classes: ItemModifier, ItemTypeClass, DyeColorClass, DyeInfo, PyItem. Enum: Rarity.

from typing import List
from typing import Tuple
from enum import IntEnum

class Rarity(IntEnum):
    White = 0
    Blue = 1
    Purple = 2
    Gold = 3
    Green = 4

class ItemModifier:
    def __init__(self, mod_value: int) -> None: ...
    def GetIdentifier(self) -> int: ...
    def GetArg1(self) -> int: ...
    def GetArg2(self) -> int: ...
    def GetArg(self) -> int: ...
    def IsValid(self) -> bool: ...
    def GetModBits(self) -> str: ...
    def ToString(self) -> str: ...

class ItemTypeClass:
    def __init__(self, type_value: int) -> None: ...
    def ToInt(self) -> int: ...
    def GetName(self) -> str: ...
    def __eq__(self, other: 'ItemTypeClass') -> bool: ...  # type: ignore[override]
    def __ne__(self, other: 'ItemTypeClass') -> bool: ...  # type: ignore[override]

class DyeColorClass:
    def __init__(self, color_value: int) -> None: ...
    def ToInt(self) -> int: ...
    def ToString(self) -> str: ...
    def __eq__(self, other: 'DyeColorClass') -> bool: ...  # type: ignore[override]
    def __ne__(self, other: 'DyeColorClass') -> bool: ...  # type: ignore[override]

class DyeInfo:
    dye_tint: int
    dye1: DyeColorClass
    dye2: DyeColorClass
    dye3: DyeColorClass
    dye4: DyeColorClass
    def __init__(self) -> None: ...
    def ToString(self) -> str: ...

class PyItem:
    item_id: int
    agent_id: int
    agent_item_id: int
    name: str
    modifiers: List[ItemModifier]
    is_customized: bool
    item_type: ItemTypeClass
    dye_info: DyeInfo
    value: int
    interaction: int
    model_id: int
    model_file_id: int
    item_formula: int
    is_material_salvageable: int
    quantity: int
    equipped: int
    profession: int
    slot: int
    is_stackable: bool
    is_inscribable: bool
    is_material: bool
    is_zcoin: bool
    rarity: Rarity
    uses: int
    is_id_kit: bool
    is_salvage_kit: bool
    is_tome: bool
    is_lesser_kit: bool
    is_expert_salvage_kit: bool
    is_perfect_salvage_kit: bool
    is_weapon: bool
    is_armor: bool
    is_salvageable: bool
    is_inventory_item: bool
    is_storage_item: bool
    is_rare_material: bool
    is_offered_in_trade: bool
    is_sparkly: bool
    is_identified: bool
    is_prefix_upgradable: bool
    is_suffix_upgradable: bool
    is_usable: bool
    is_tradable: bool
    is_inscription: bool
    is_rarity_blue: bool
    is_rarity_purple: bool
    is_rarity_green: bool
    is_rarity_gold: bool

    def __init__(self, item_id: int) -> None: ...
    def GetContext(self) -> None: ...
    def RequestName(self) -> None: ...
    def IsItemNameReady(self) -> bool: ...
    def GetName(self) -> str: ...
    def GetInfoString(self) -> List[int]: ...
    def GetNameEnc(self) -> List[int]: ...
    def GetCompleteNameEnc(self) -> List[int]: ...
    def GetSingleItemName(self) -> List[int]: ...
    def IsItemValid(self, id: int) -> bool: ...

    # Takes a model_file_id (not an item id); returns the composite model file ids.
    @staticmethod
    def GetCompositeModelIDs(model_file_id: int) -> List[int]: ...

# ── Module-level free functions ──
def use_item_by_id(item_id: int) -> bool: ...
def equip_item_by_id(item_id: int, agent_id: int = 0) -> bool: ...
def drop_item_by_id(item_id: int, quantity: int) -> bool: ...
def pick_up_item_by_id(item_id: int, call_target: int = 0) -> bool: ...
def move_item(item_id: int, bag_id: int, slot: int, quantity: int = 0) -> bool: ...
def use_item_by_model_id(model_id: int, bag_start: int = 1, bag_end: int = 4) -> bool: ...
def count_item_by_model_id(model_id: int, bag_start: int = 1, bag_end: int = 4) -> int: ...

# ── Gold ──
def get_gold_amount_on_character() -> int: ...
def get_gold_amount_in_storage() -> int: ...
def drop_gold(amount: int = 1) -> bool: ...
def deposit_gold(amount: int = 0) -> int: ...
def withdraw_gold(amount: int = 0) -> int: ...
def change_gold(character_gold: int, storage_gold: int) -> bool: ...

# ── Salvage / identify / destroy ──
def salvage_start(salvage_kit_id: int, item_id: int) -> bool: ...
def identify_item(identification_kit_id: int, item_id: int) -> bool: ...
def salvage_session_cancel() -> bool: ...
def salvage_session_done() -> bool: ...
def destroy_item(item_id: int) -> bool: ...
def salvage_materials() -> bool: ...

# ── Storage / Xunlai chest ──
def open_xunlai_window(anniversary_pane_unlocked: bool = True) -> None: ...
def get_storage_page() -> int: ...
def get_is_storage_open() -> bool: ...
def can_access_xunlai_chest() -> bool: ...
def get_material_storage_stack_size() -> int: ...

# ── Static PvP-unlock (item-mod) table ──
# The game's authoritative upgrade-component table (weapon prefixes/suffixes, runes,
# insignias, inscriptions). get_pvp_unlock_name_enc returns the game-composed ENCODED
# (name, description) byte arrays for an unlock index; decode with string_table.
# NOTE: the binding declares no py::arg, so the index is positional-only.
def get_pvp_unlock_count() -> int: ...
def get_pvp_unlock_name_enc(unlock_index: int, /) -> Tuple[List[int], List[int]]: ...
