# PyPing stub — Reforged Native surface
# Matches src/GW/ping/ping_bindings.cpp.
# The C++ class is GW::ping::PingTracker, exposed to Python as "PingHandler".
# Only the default constructor is bound (history size fixed at the C++ default).

class PingHandler:
    def __init__(self) -> None: ...
    def Terminate(self) -> None: ...
    def GetCurrentPing(self) -> int: ...
    def GetAveragePing(self) -> int: ...
    def GetMinPing(self) -> int: ...
    def GetMaxPing(self) -> int: ...
