# PySkillbar.pyi - type stub for the PySkillbar embedded module.
#
# Mirrors src/GW/skillbar/skillbar_bindings.cpp exactly.
# The module exposes two classes (SkillbarSkill, Skillbar) and a set of
# module-level free functions. No enums are exposed by this module.

from typing import Any
from typing import Dict
from typing import List

from PySkill import SkillID

# Class SkillbarSkill - a single skillbar slot (GW::Context::SkillbarSkill).
# All members are read-only. The binding declares no py::init, so instances can
# only be obtained from Skillbar.skills / Skillbar.GetSkill / GetHeroSkillbar.
class SkillbarSkill:
    id: SkillID  # def_property_readonly -> PySkill.SkillID
    adrenaline_a: int
    adrenaline_b: int
    recharge: int
    event: int
    get_recharge: int  # def_property_readonly (a property, not a method)

# Class Skillbar - snapshot of the player's skillbar taken at construction.
# Data members are read-only properties over the snapshot; GetContext() refreshes it.
class Skillbar:
    agent_id: int
    disabled: int
    casting: int
    skills: List[SkillbarSkill]

    def __init__(self) -> None: ...
    def GetContext(self) -> None: ...
    def GetSkill(self, slot: int) -> SkillbarSkill: ...
    def LoadSkillTemplate(self, skill_template: str) -> bool: ...
    def LoadHeroSkillTemplate(self, hero_index: int, skill_template: str) -> bool: ...
    def UseSkill(self, slot: int, target: int = 0) -> bool: ...
    def UseSkillTargetless(self, slot: int) -> bool: ...
    def HeroUseSkill(self, target_agent_id: int, skill_number: int, hero_idx: int) -> bool: ...
    def ChangeHeroSecondary(self, hero_index: int, profession: int) -> bool: ...
    def GetHeroSkillbar(self, hero_index: int) -> List[SkillbarSkill]: ...
    def GetHoveredSkill(self) -> int: ...
    def IsSkillUnlocked(self, skill_id: int) -> bool: ...
    def IsSkillLearnt(self, skill_id: int) -> bool: ...

# --- module-level free functions ---

def get_skill_slot(skill_id: int) -> int: ...
def use_skill(slot: int, target: int = 0) -> bool: ...
def point_blank_use_skill(slot: int) -> bool: ...
def use_skill_by_id(skill_id: int, target: int = 0) -> bool: ...
def get_is_skill_unlocked(skill_id: int) -> bool: ...
def get_is_skill_learnt(skill_id: int) -> bool: ...
def get_skill_profession(skill_id: int) -> int: ...

# Skill icon file ids (GW.dat texture ids). icon_file_id is the primary icon;
# the hi-res id is the larger variant. Feed either to
# PyTexture.get_texture_by_file_id or a "gwdat://<id>" key. Returns 0 if unknown.
def get_skill_icon_file_id(skill_id: int) -> int: ...
def get_skill_icon_file_id_hi_res(skill_id: int) -> int: ...
def get_attribute_profession(attribute_id: int) -> int: ...
def change_second_profession(profession: int, hero_index: int = 0) -> bool: ...
def load_skill_template(template: str, hero_index: int = 0) -> bool: ...
def load_skillbar(skill_ids: List[int], hero_index: int = 0) -> bool: ...
def set_attributes(attribute_ids: List[int], attribute_values: List[int], hero_index: int = 0) -> bool: ...
def encode_skill_template(hero_index: int = 0) -> str: ...

# Returns {} on decode failure, otherwise:
#   {"profession": int, "secondary_profession": int,
#    "skills": List[int] (8 entries),
#    "attributes": List[{"id": int, "level": int}] (non-None attributes only)}
def decode_skill_template(template: str) -> Dict[str, Any]: ...
def get_hovered_skill_id() -> int: ...
def hero_use_skill(target_agent_id: int, skill_number: int, hero_index: int) -> bool: ...
